export const menuData = [
  {
    name: "Valentina's Egg Beaters",
    description: 'Served with Tabasco en flambé',
    price: '$6.99',
    course: 'main',
  },
  {
    name: "Adrianna's Cheez Dogz",
    description: 'Served beneath 1 full can of Cheez Whiz',
    price: '$11.99',
    course: 'main',
  },
  {
    name: "Tony's Fucking Lo Mein",
    description: 'Generous Portion for guaranteed leftovers',
    price: '$7.99',
    course: 'main',
  },
  {
    name: 'Sushi with Cayenne Peppah',
    description: 'Perfect for a Date Night',
    price: '$11.99',
    course: 'main',
  },
  {
    name: "Livia's Fuckin' Ziti",
    description: 'Birthday Party sized tray',
    price: '$29.99',
    course: 'main',
  },
  {
    name: 'Lincoln Log Sandwich',
    description: 'Guaranteed to turn frowns upside down',
    price: '$4.99',
    course: 'main',
  },
  {
    name: "New Jersey's Greatest Sangwich",
    description: 'One daily; delivery by Christopher',
    price: '$9.99',
    course: 'main',
  },
  {
    name: 'Scrambled Eggs with Sour Cream',
    description: 'So good, this could be your last meal!',
    price: '$5.99',
    course: 'main',
  },
  {
    name: "Artie's Zuppa di Mussels",
    description: 'Definitely fresh',
    price: '$25.99',
    course: 'main',
  },
  {
    name: 'Peppahs and Eggs Sandwich',
    description: "If you don't order this, you'll wish you did!",
    price: '$9.99',
    course: 'main',
  },
  {
    name: 'Grilled Cheese',
    description: 'Prepared on an antique jailhouse radiator',
    price: '$9.99',
    course: 'main',
  },
  {
    name: 'Macaroni and Gravy',
    description: 'Commendatori!',
    price: '$14.99',
    course: 'main',
  },
  {
    name: 'Quail a la Bucco',
    description: 'Stuffed with fennel',
    price: '$27.99',
    course: 'main',
  },
  {
    name: "Motherfuckin' Goddamn Orange Peel Beef",
    description: 'Make sure you check your order',
    price: '$11.99',
    course: 'main',
  },
  {
    name: "Janice's Carmela's Lasagna",
    description: 'Bits of sweet sausage, basil under the cheese',
    price: '$19.99',
    course: 'main',
  },
  {
    name: "Junior's Favorite Spicy Chicken",
    description: 'Worth leaving the house for',
    price: '$14.99',
    course: 'main',
  },
  {
    name: "Gloria Trillo's London Broil",
    description: 'Aged 4 hours, served mid-air',
    price: '$22.99',
    course: 'main',
  },
  {
    name: "Karen's Last Ziti",
    description: 'Prepared fresh, frozen for months',
    price: '$19.99',
    course: 'main',
  },
  {
    name: 'Stripclub Wedge of Jarslberg',
    description: 'Aged at The Bing',
    price: '$15.99',
    course: 'appetizers',
  },
  {
    name: "Sil's Bread",
    description: 'Fresh from the Bread Museum',
    price: '$4.99',
    course: 'appetizers',
  },
  {
    name: 'Burrata and Green Beans',
    description: "It's nutty",
    price: '$10.99',
    course: 'appetizers',
  },
  {
    name: 'The Gabagool',
    description: "So good, you'll faint!",
    price: '$8.99',
    course: 'appetizers',
  },
  {
    name: 'House Smoked Mozzarella',
    description: 'The secret is in the ashes',
    price: '$8.99',
    course: 'appetizers',
  },
  {
    name: 'The Last Supper Onion Rings',
    description: "Best in state, as far as I'm concerned",
    price: '$10.99',
    course: 'appetizers',
  },
  {
    name: "Meadow's Summertime Hot Chili",
    description: "It's really good chili",
    price: '$4.99',
    course: 'appetizers',
  },
];

export const desserts = [
  {
    name: "Hugh's Favorite Maple Walnut Icebox Cake",
    description: 'Only available during peak hours',
    price: '$8.99',
  },
  {
    name: 'Giant Bowl of Ice Cream',
    description: 'Perfect post-workout snack',
    price: '$8.99',
  },
  {
    name: "Mary DeAngelis' Pound Cake",
    description: 'Made with canned pears',
    price: '$8.99',
  },
  {
    name: 'Ricotta Pie ',
    description: 'With pineapple and high school transcripts',
    price: '$8.99',
  },
  {
    name: "Whitman's Sampler",
    description: 'Guaranteed to make you feel better',
    price: '$11.99',
  },
  {
    name: 'Orange Juice',
    description: 'Has some pulp',
    price: '$1.99',
    course: 'drinks',
  },
  {
    name: 'Scotch',
    description: 'Served on the rocks',
    price: '$10.99',
    course: 'drinks',
  },
  {
    name: 'Appletini',
    description: 'Served La Cerva style',
    price: '$8.99',
    course: 'drinks',
  },
  {
    name: 'Communion Wine',
    description: 'Confession has never been easier!',
    price: '$5.99',
    course: 'drinks',
  },
  {
    name: 'Armagnac',
    description: "It's the next vodka",
    price: '$25.99',
    course: 'drinks',
  },
  {
    name: 'Diet Coke',
    description: 'Only available in 12oz cans',
    price: '$1.99',
    course: 'drinks',
  },
  {
    name: 'The Martina',
    description: 'Like a martini but from Albania',
    price: '$9.99',
    course: 'drinks',
  },
  {
    name: 'Dirty Martini',
    description: 'Mostly olives',
    price: '$9.99',
    course: 'drinks',
  },
];
